// client/src/components/AuthModal.jsx
import React, { useState } from 'react';
import { X, Lock, Mail, User, Shield } from 'lucide-react';
import { api } from '../services/api';

export function AuthModal({ isOpen, onClose, onAuthSuccess, addToast }) {
  const [isRegister, setIsRegister] = useState(false);
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [role, setRole] = useState('customer');
  const [loading, setLoading] = useState(false);

  if (!isOpen) return null;

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);

    try {
      let res;
      if (isRegister) {
        res = await api.auth.register({ name, email, password, role });
        addToast('success', 'Account Registered', `Welcome, ${name}!`);
      } else {
        res = await api.auth.login({ email, password });
        addToast('success', 'Logged In', `Welcome back, ${res.data.name}!`);
      }

      if (res.data.token) {
        localStorage.setItem('helpdesk_token', res.data.token);
      }

      onAuthSuccess(res.data);
      onClose();
    } catch (err) {
      addToast('error', 'Authentication Failed', err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()} style={{ maxWidth: '440px', padding: '24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '18px' }}>
          <div>
            <h3 style={{ fontSize: '18px', fontWeight: '800', color: '#fff' }}>
              {isRegister ? 'Create Helpdesk Account' : 'Sign In to Helpdesk'}
            </h3>
            <p style={{ fontSize: '12px', color: 'var(--text-muted)' }}>
              {isRegister ? 'Register your role credentials' : 'Access your role-based ticketing workspace'}
            </p>
          </div>
          <button onClick={onClose} style={{ background: 'transparent', border: 'none', color: 'var(--text-subtle)', cursor: 'pointer' }}>
            <X size={20} />
          </button>
        </div>

        <form onSubmit={handleSubmit}>
          {isRegister && (
            <div className="form-group">
              <label className="form-label">Full Name</label>
              <input
                type="text"
                className="form-input"
                placeholder="e.g. Alex Johnson"
                value={name}
                onChange={(e) => setName(e.target.value)}
                required
              />
            </div>
          )}

          <div className="form-group">
            <label className="form-label">Email Address</label>
            <input
              type="email"
              className="form-input"
              placeholder="e.g. user@helpdesk.com"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
            />
          </div>

          <div className="form-group">
            <label className="form-label">Password</label>
            <input
              type="password"
              className="form-input"
              placeholder="Password@123"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
            />
          </div>

          {isRegister && (
            <div className="form-group">
              <label className="form-label">Select System Role</label>
              <select className="form-select" value={role} onChange={(e) => setRole(e.target.value)}>
                <option value="customer">Customer (Raise tickets & rate)</option>
                <option value="agent">Support Agent (Troubleshoot & resolve)</option>
                <option value="manager">Manager / Admin (Dispatch & SLA reports)</option>
              </select>
            </div>
          )}

          <button type="submit" disabled={loading} className="btn btn-primary" style={{ width: '100%', marginTop: '10px' }}>
            {loading ? 'Processing...' : isRegister ? 'Register Account' : 'Sign In'}
          </button>

          <div style={{ textAlign: 'center', marginTop: '16px', fontSize: '13px', color: 'var(--text-muted)' }}>
            {isRegister ? 'Already have an account? ' : "Don't have an account? "}
            <button
              type="button"
              onClick={() => setIsRegister(!isRegister)}
              style={{ background: 'transparent', border: 'none', color: 'var(--cyan)', fontWeight: '700', cursor: 'pointer' }}
            >
              {isRegister ? 'Sign In' : 'Register Now'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

// client/src/app/components/auth-modal/auth-modal.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-auth-modal',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="modal-overlay" (click)="close.emit()">
      <div class="modal-content" (click)="$event.stopPropagation()">
        <!-- Header -->
        <div class="modal-header">
          <h3 class="modal-title">{{ isRegister ? 'Create Helpdesk Account' : 'Sign In to Helpdesk' }}</h3>
          <button (click)="close.emit()" class="close-btn">&times;</button>
        </div>

        <!-- Tab Switcher -->
        <div class="tab-bar">
          <button [class.active]="!isRegister" (click)="isRegister = false" class="tab-btn">Sign In</button>
          <button [class.active]="isRegister" (click)="isRegister = true" class="tab-btn">Register New Account</button>
        </div>

        <form (ngSubmit)="onSubmit()">
          <!-- Registration Fields -->
          <div *ngIf="isRegister" class="form-group">
            <label class="form-label">Full Name</label>
            <input type="text" [(ngModel)]="name" name="name" required class="form-input" placeholder="e.g. John Doe" />
          </div>

          <div class="form-group">
            <label class="form-label">Email Address</label>
            <input type="email" [(ngModel)]="email" name="email" required class="form-input" placeholder="user@helpdesk.com" />
          </div>

          <div class="form-group">
            <label class="form-label">Password</label>
            <input type="password" [(ngModel)]="password" name="password" required class="form-input" placeholder="••••••••" />
          </div>

          <div *ngIf="isRegister" class="form-group">
            <label class="form-label">Role</label>
            <select [(ngModel)]="role" name="role" class="form-select">
              <option value="customer">Customer</option>
              <option value="agent">Support Agent</option>
              <option value="manager">Manager</option>
            </select>
          </div>

          <button type="submit" [disabled]="loading" class="btn btn-primary" style="width: 100%; margin-top: 0.5rem;">
            {{ loading ? 'Processing...' : (isRegister ? 'Create Account' : 'Sign In') }}
          </button>
        </form>

        <!-- Quick Demo Switcher -->
        <div class="demo-section">
          <div class="demo-title">Or Fast Sign-In as Seeded Account:</div>
          <div class="demo-grid">
            <button 
              *ngFor="let p of auth.personas" 
              (click)="fastLogin(p.email)" 
              class="btn btn-secondary btn-sm"
            >
              {{ p.label }} ({{ p.badge }})
            </button>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .modal-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 1.25rem;
    }
    .modal-title {
      font-size: 1.25rem;
      font-weight: 700;
    }
    .close-btn {
      background: none;
      border: none;
      color: var(--text-muted);
      font-size: 1.5rem;
      cursor: pointer;
    }
    .close-btn:hover { color: var(--text-primary); }

    .tab-bar {
      display: flex;
      background: rgba(0, 0, 0, 0.4);
      border-radius: var(--radius-md);
      padding: 0.25rem;
      margin-bottom: 1.25rem;
      border: 1px solid var(--border-subtle);
    }
    .tab-btn {
      flex: 1;
      padding: 0.5rem;
      font-size: 0.85rem;
      font-weight: 600;
      background: transparent;
      border: none;
      color: var(--text-secondary);
      border-radius: var(--radius-sm);
      cursor: pointer;
      transition: all 0.2s;
    }
    .tab-btn.active {
      background: var(--indigo);
      color: #ffffff;
      box-shadow: 0 2px 8px var(--indigo-glow);
    }

    .demo-section {
      margin-top: 1.5rem;
      padding-top: 1.25rem;
      border-top: 1px solid var(--border-subtle);
    }
    .demo-title {
      font-size: 0.75rem;
      font-weight: 700;
      color: var(--text-muted);
      text-transform: uppercase;
      letter-spacing: 0.05em;
      margin-bottom: 0.75rem;
    }
    .demo-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 0.5rem;
    }
  `]
})
export class AuthModalComponent {
  @Output() close = new EventEmitter<void>();

  isRegister = false;
  email = '';
  password = 'Password@123';
  name = '';
  role = 'customer';
  loading = false;

  constructor(public auth: AuthService) {}

  async onSubmit() {
    this.loading = true;
    let success = false;
    if (this.isRegister) {
      success = await this.auth.register({
        name: this.name,
        email: this.email,
        password: this.password,
        role: this.role
      });
    } else {
      success = await this.auth.login(this.email, this.password);
    }
    this.loading = false;
    if (success) {
      this.close.emit();
    }
  }

  async fastLogin(email: string) {
    this.loading = true;
    const success = await this.auth.loginAsPersona(email);
    this.loading = false;
    if (success) {
      this.close.emit();
    }
  }
}
