// client/src/app/components/ticket-detail-modal/ticket-detail-modal.component.ts
import { Component, EventEmitter, Input, OnInit, OnDestroy, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Ticket, CommentItem, Rating, User } from '../../models/types';
import { ApiService } from '../../services/api.service';
import { SocketService } from '../../services/socket.service';
import { ToastService } from '../../services/toast.service';
import { AuthService } from '../../services/auth.service';
import { Subscription } from 'rxjs';
import confetti from 'canvas-confetti';

@Component({
  selector: 'app-ticket-detail-modal',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="modal-overlay" (click)="close.emit()">
      <div class="modal-content modal-large" (click)="$event.stopPropagation()">
        <!-- Header -->
        <div class="modal-header">
          <div class="header-main">
            <div class="badges-row">
              <span class="badge" [ngClass]="'badge-' + ticket.status.toLowerCase().replace(' ', '-')">{{ ticket.status }}</span>
              <span class="badge" [ngClass]="'badge-' + ticket.priority.toLowerCase()">{{ ticket.priority }}</span>
              <span class="badge badge-secondary">{{ ticket.category }}</span>
              <span *ngIf="ticket.isEscalated" class="badge badge-urgent">⚠️ ESCALATED</span>
              <span *ngIf="isBreached()" class="badge badge-breached">⏰ SLA BREACHED</span>
            </div>
            <h2 class="ticket-title">{{ ticket.title }}</h2>
            <div class="ticket-meta">
              <span>Created by <strong>{{ getCustomerName() }}</strong></span>
              <span>•</span>
              <span>Assigned: <strong>{{ getAgentName() }}</strong></span>
              <span>•</span>
              <span>Target SLA: <strong>{{ formatSlaDue() }}</strong></span>
            </div>
          </div>
          <button (click)="close.emit()" class="close-btn">&times;</button>
        </div>

        <!-- Description Box -->
        <div class="description-box">
          <div class="box-title">Description</div>
          <p class="description-text">{{ ticket.description }}</p>
          <div *ngIf="ticket.isEscalated && ticket.escalationReason" class="escalation-alert">
            <strong>Escalation Reason:</strong> {{ ticket.escalationReason }}
          </div>
        </div>

        <!-- Staff Action Toolbar (Agent, Manager, Admin) -->
        <div *ngIf="isStaff()" class="staff-toolbar">
          <div class="toolbar-title">Staff State Machine & Workflow Controls</div>
          <div class="toolbar-actions">
            <!-- Status Transitions -->
            <button 
              *ngIf="ticket.status === 'Open'" 
              (click)="changeStatus('In Progress')"
              class="btn btn-primary btn-sm"
            >
              Start Progress
            </button>

            <button 
              *ngIf="ticket.status === 'In Progress'" 
              (click)="changeStatus('On Hold')"
              class="btn btn-warning btn-sm"
            >
              Put On Hold
            </button>

            <button 
              *ngIf="ticket.status === 'On Hold'" 
              (click)="changeStatus('In Progress')"
              class="btn btn-primary btn-sm"
            >
              Resume Work
            </button>

            <button 
              *ngIf="ticket.status === 'In Progress' || ticket.status === 'On Hold'" 
              (click)="changeStatus('Resolved')"
              class="btn btn-success btn-sm"
            >
              Mark Resolved
            </button>

            <button 
              *ngIf="ticket.status === 'Resolved' && (auth.currentUser?.role === 'manager' || auth.currentUser?.role === 'admin')" 
              (click)="changeStatus('Closed')"
              class="btn btn-secondary btn-sm"
            >
              Close Ticket
            </button>

            <!-- Auto-Assign -->
            <button 
              *ngIf="!ticket.assignedAgentId" 
              (click)="autoAssign()"
              class="btn btn-secondary btn-sm"
            >
              ⚡ Auto-Assign Agent
            </button>

            <!-- Escalate -->
            <button 
              *ngIf="!ticket.isEscalated && ticket.status !== 'Closed'" 
              (click)="promptEscalate()"
              class="btn btn-danger btn-sm"
            >
              🔺 Escalate Ticket
            </button>
          </div>
        </div>

        <!-- Customer Rating Widget (for Resolved / Closed Tickets) -->
        <div *ngIf="auth.currentUser?.role === 'customer' && (ticket.status === 'Resolved' || ticket.status === 'Closed')" class="rating-box">
          <div class="box-title">⭐ Customer Satisfaction (CSAT) Rating</div>
          <ng-container *ngIf="existingRating; else ratingForm">
            <div class="existing-rating">
              <div class="stars">
                <span *ngFor="let s of [1,2,3,4,5]" class="star filled">{{ s <= existingRating.score ? '★' : '☆' }}</span>
              </div>
              <p *ngIf="existingRating.comment" class="rating-comment">"{{ existingRating.comment }}"</p>
              <div class="rating-note">Thank you! Your feedback helps our support team improve.</div>
            </div>
          </ng-container>

          <ng-template #ratingForm>
            <div class="rating-input-group">
              <div class="star-selector">
                <button 
                  *ngFor="let s of [1,2,3,4,5]" 
                  type="button" 
                  (click)="selectedScore = s"
                  class="star-btn"
                  [class.active]="s <= selectedScore"
                >
                  ★
                </button>
              </div>
              <input 
                type="text" 
                [(ngModel)]="ratingComment" 
                class="form-input rating-input" 
                placeholder="Optional feedback comment on resolution quality..."
              />
              <button (click)="submitRating()" [disabled]="ratingLoading" class="btn btn-success btn-sm">
                {{ ratingLoading ? 'Submitting...' : 'Submit Rating' }}
              </button>
            </div>
          </ng-template>
        </div>

        <!-- Comments Stream -->
        <div class="comments-section">
          <div class="comments-header">
            <div class="box-title">
              Conversation Thread ({{ comments.length }})
            </div>
            <!-- Staff tab filter -->
            <div *ngIf="isStaff()" class="comment-tabs">
              <button [class.active]="commentFilter === 'all'" (click)="commentFilter = 'all'" class="c-tab">All</button>
              <button [class.active]="commentFilter === 'internal'" (click)="commentFilter = 'internal'" class="c-tab">🔒 Internal Only</button>
            </div>
          </div>

          <!-- Comment List -->
          <div class="comment-list">
            <div *ngIf="filteredComments().length === 0" class="empty-comments">
              No comments yet. Start the conversation below.
            </div>

            <div 
              *ngFor="let c of filteredComments()" 
              class="comment-card" 
              [class.internal-note]="c.isInternal"
            >
              <div class="comment-meta">
                <div class="comment-author">
                  <span class="c-avatar">{{ getAuthorInitials(c) }}</span>
                  <span class="c-name">{{ getAuthorName(c) }}</span>
                  <span class="badge badge-sm" [ngClass]="'badge-' + getAuthorRole(c)">{{ getAuthorRole(c) }}</span>
                  <span *ngIf="c.isInternal" class="badge badge-warning badge-sm">🔒 INTERNAL NOTE</span>
                </div>
                <span class="comment-time">{{ formatTime(c.createdAt) }}</span>
              </div>
              <p class="comment-message">{{ c.message }}</p>
            </div>
          </div>

          <!-- Add Comment Box -->
          <form (ngSubmit)="postComment()" class="comment-form">
            <div class="input-row">
              <input 
                type="text" 
                [(ngModel)]="newCommentMessage" 
                name="newComment" 
                class="form-input" 
                placeholder="Write a reply or status update..."
                required
              />
              <button type="submit" [disabled]="commentLoading || !newCommentMessage.trim()" class="btn btn-primary">
                {{ commentLoading ? 'Posting...' : 'Send' }}
              </button>
            </div>

            <!-- Internal Note Checkbox for Staff -->
            <div *ngIf="isStaff()" class="internal-toggle">
              <label class="checkbox-label">
                <input type="checkbox" [(ngModel)]="isInternalNote" name="isInternalNote" />
                <span class="toggle-text">🔒 Post as Staff Private Internal Note (strictly hidden from customer)</span>
              </label>
            </div>
          </form>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .modal-large {
      max-width: 800px;
    }

    .modal-header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 1.25rem;
      border-bottom: 1px solid var(--border-subtle);
      padding-bottom: 1rem;
    }

    .badges-row {
      display: flex;
      gap: 0.5rem;
      align-items: center;
      margin-bottom: 0.5rem;
      flex-wrap: wrap;
    }

    .ticket-title {
      font-size: 1.35rem;
      font-weight: 800;
      color: #ffffff;
      margin-bottom: 0.35rem;
    }

    .ticket-meta {
      display: flex;
      gap: 0.6rem;
      font-size: 0.775rem;
      color: var(--text-muted);
      flex-wrap: wrap;
    }

    .ticket-meta strong {
      color: var(--text-secondary);
    }

    .close-btn {
      background: none;
      border: none;
      color: var(--text-muted);
      font-size: 1.75rem;
      cursor: pointer;
    }
    .close-btn:hover { color: var(--text-primary); }

    .description-box {
      background: rgba(0, 0, 0, 0.25);
      border: 1px solid var(--border-subtle);
      border-radius: var(--radius-md);
      padding: 1rem;
      margin-bottom: 1.25rem;
    }

    .box-title {
      font-size: 0.75rem;
      font-weight: 700;
      color: var(--text-muted);
      text-transform: uppercase;
      letter-spacing: 0.05em;
      margin-bottom: 0.4rem;
    }

    .description-text {
      font-size: 0.9rem;
      line-height: 1.6;
      color: var(--text-primary);
    }

    .escalation-alert {
      margin-top: 0.75rem;
      padding: 0.5rem 0.75rem;
      background: rgba(244, 63, 94, 0.15);
      border-left: 3px solid var(--rose);
      border-radius: var(--radius-sm);
      font-size: 0.8rem;
      color: #ffffff;
    }

    .staff-toolbar {
      background: rgba(99, 102, 241, 0.08);
      border: 1px solid rgba(99, 102, 241, 0.25);
      border-radius: var(--radius-md);
      padding: 0.85rem 1rem;
      margin-bottom: 1.25rem;
    }

    .toolbar-title {
      font-size: 0.75rem;
      font-weight: 700;
      color: var(--indigo);
      margin-bottom: 0.6rem;
      text-transform: uppercase;
    }

    .toolbar-actions {
      display: flex;
      gap: 0.5rem;
      flex-wrap: wrap;
    }

    .rating-box {
      background: rgba(245, 158, 11, 0.08);
      border: 1px solid rgba(245, 158, 11, 0.3);
      border-radius: var(--radius-md);
      padding: 1rem;
      margin-bottom: 1.25rem;
    }

    .rating-input-group {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      flex-wrap: wrap;
    }

    .star-selector {
      display: flex;
      gap: 0.25rem;
    }

    .star-btn {
      background: none;
      border: none;
      font-size: 1.5rem;
      color: var(--text-muted);
      cursor: pointer;
      transition: all 0.2s;
    }

    .star-btn.active {
      color: var(--amber);
      transform: scale(1.15);
    }

    .rating-input {
      flex: 1;
      min-width: 200px;
    }

    .existing-rating .stars {
      font-size: 1.5rem;
      color: var(--amber);
      margin: 0.25rem 0;
    }

    .rating-comment {
      font-style: italic;
      font-size: 0.875rem;
      color: var(--text-primary);
    }

    .rating-note {
      font-size: 0.75rem;
      color: var(--emerald);
      margin-top: 0.25rem;
    }

    .comments-section {
      background: rgba(0, 0, 0, 0.25);
      border: 1px solid var(--border-subtle);
      border-radius: var(--radius-md);
      padding: 1rem;
    }

    .comments-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 0.75rem;
    }

    .comment-tabs {
      display: flex;
      gap: 0.25rem;
      background: rgba(0, 0, 0, 0.3);
      padding: 0.15rem;
      border-radius: var(--radius-sm);
    }

    .c-tab {
      background: none;
      border: none;
      padding: 0.2rem 0.5rem;
      font-size: 0.7rem;
      font-weight: 600;
      color: var(--text-muted);
      border-radius: var(--radius-sm);
      cursor: pointer;
    }

    .c-tab.active {
      background: rgba(255, 255, 255, 0.1);
      color: var(--text-primary);
    }

    .comment-list {
      max-height: 280px;
      overflow-y: auto;
      display: flex;
      flex-direction: column;
      gap: 0.75rem;
      margin-bottom: 1rem;
      padding-right: 0.5rem;
    }

    .empty-comments {
      text-align: center;
      padding: 1.5rem;
      color: var(--text-muted);
      font-size: 0.85rem;
    }

    .comment-card {
      background: rgba(255, 255, 255, 0.03);
      border: 1px solid var(--border-subtle);
      border-radius: var(--radius-md);
      padding: 0.75rem 0.85rem;
    }

    .comment-card.internal-note {
      background: rgba(245, 158, 11, 0.08);
      border-color: rgba(245, 158, 11, 0.3);
    }

    .comment-meta {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 0.4rem;
    }

    .comment-author {
      display: flex;
      align-items: center;
      gap: 0.4rem;
    }

    .c-avatar {
      width: 20px;
      height: 20px;
      border-radius: 50%;
      background: var(--indigo);
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 0.65rem;
      font-weight: 700;
    }

    .c-name {
      font-size: 0.8rem;
      font-weight: 700;
    }

    .badge-sm {
      font-size: 0.65rem;
      padding: 0.05rem 0.35rem;
    }

    .comment-time {
      font-size: 0.7rem;
      color: var(--text-muted);
    }

    .comment-message {
      font-size: 0.85rem;
      line-height: 1.5;
      color: var(--text-primary);
    }

    .comment-form .input-row {
      display: flex;
      gap: 0.5rem;
    }

    .internal-toggle {
      margin-top: 0.5rem;
    }

    .checkbox-label {
      display: flex;
      align-items: center;
      gap: 0.4rem;
      font-size: 0.75rem;
      color: var(--amber);
      cursor: pointer;
    }
  `]
})
export class TicketDetailModalComponent implements OnInit, OnDestroy {
  @Input() ticket!: Ticket;
  @Output() close = new EventEmitter<void>();
  @Output() updated = new EventEmitter<void>();

  comments: CommentItem[] = [];
  commentFilter: 'all' | 'internal' = 'all';
  newCommentMessage = '';
  isInternalNote = false;
  commentLoading = false;

  selectedScore = 5;
  ratingComment = '';
  ratingLoading = false;
  existingRating: Rating | null = null;

  private subs: Subscription[] = [];

  constructor(
    public auth: AuthService,
    private api: ApiService,
    private socket: SocketService,
    private toast: ToastService
  ) {}

  ngOnInit() {
    this.socket.joinTicketRoom(this.ticket._id);
    this.loadComments();
    this.loadRating();

    // Listen to real-time comments
    this.subs.push(
      this.socket.commentAdded$.subscribe((data) => {
        if (data && data.ticketId === this.ticket._id) {
          this.loadComments();
        }
      }),
      this.socket.commentInternalNote$.subscribe((data) => {
        if (data && data.ticketId === this.ticket._id) {
          this.loadComments();
        }
      })
    );
  }

  ngOnDestroy() {
    this.socket.leaveTicketRoom(this.ticket._id);
    this.subs.forEach(s => s.unsubscribe());
  }

  async loadComments() {
    try {
      const res = await this.api.comments.list(this.ticket._id);
      if (res.success) {
        this.comments = res.data;
      }
    } catch (err: any) {
      console.warn('Failed to load comments:', err.message);
    }
  }

  async loadRating() {
    if (this.ticket.status === 'Resolved' || this.ticket.status === 'Closed') {
      try {
        const res = await this.api.ratings.getByTicket(this.ticket._id);
        if (res.success && res.data) {
          this.existingRating = res.data;
        }
      } catch {
        this.existingRating = null;
      }
    }
  }

  filteredComments(): CommentItem[] {
    if (this.commentFilter === 'internal') {
      return this.comments.filter(c => c.isInternal);
    }
    return this.comments;
  }

  isStaff(): boolean {
    const role = this.auth.currentUser?.role;
    return role === 'agent' || role === 'manager' || role === 'admin';
  }

  getCustomerName(): string {
    if (typeof this.ticket.customerId === 'object' && this.ticket.customerId) {
      return this.ticket.customerId.name;
    }
    return 'Customer';
  }

  getAgentName(): string {
    if (typeof this.ticket.assignedAgentId === 'object' && this.ticket.assignedAgentId) {
      return this.ticket.assignedAgentId.name;
    }
    return 'Unassigned';
  }

  getAuthorName(c: CommentItem): string {
    if (typeof c.authorId === 'object' && c.authorId) {
      return c.authorId.name;
    }
    return 'User';
  }

  getAuthorRole(c: CommentItem): string {
    if (typeof c.authorId === 'object' && c.authorId) {
      return c.authorId.role;
    }
    return 'user';
  }

  getAuthorInitials(c: CommentItem): string {
    return this.getAuthorName(c).charAt(0).toUpperCase();
  }

  isBreached(): boolean {
    if (this.ticket.status === 'Resolved' || this.ticket.status === 'Closed') {
      return false;
    }
    if (!this.ticket.slaDueAt) return false;
    return new Date(this.ticket.slaDueAt).getTime() < Date.now();
  }

  formatSlaDue(): string {
    if (!this.ticket.slaDueAt) return 'No SLA Target';
    const due = new Date(this.ticket.slaDueAt);
    return due.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', month: 'short', day: 'numeric' });
  }

  formatTime(dateStr: string): string {
    if (!dateStr) return '';
    return new Date(dateStr).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  }

  async changeStatus(newStatus: string) {
    try {
      const res = await this.api.tickets.updateStatus(this.ticket._id, newStatus);
      if (res.success) {
        this.ticket.status = newStatus;
        this.toast.success(`Ticket transitioned to ${newStatus}`);
        this.updated.emit();
      }
    } catch (err: any) {
      this.toast.error(err.message || 'Status transition rejected by State Machine');
    }
  }

  async autoAssign() {
    try {
      const res = await this.api.tickets.autoAssign(this.ticket._id);
      if (res.success) {
        this.ticket = res.data;
        this.toast.success('Agent automatically assigned by workload engine');
        this.updated.emit();
      }
    } catch (err: any) {
      this.toast.error(err.message || 'Auto-assignment failed');
    }
  }

  async promptEscalate() {
    const reason = prompt('Please provide the escalation justification reason:');
    if (reason && reason.trim()) {
      try {
        const res = await this.api.tickets.escalate(this.ticket._id, reason.trim());
        if (res.success) {
          this.ticket.isEscalated = true;
          this.ticket.escalationReason = reason.trim();
          this.toast.warning('Ticket escalated to Senior Management');
          this.updated.emit();
        }
      } catch (err: any) {
        this.toast.error(err.message || 'Escalation failed');
      }
    }
  }

  async postComment() {
    if (!this.newCommentMessage.trim()) return;
    this.commentLoading = true;
    try {
      const res = await this.api.comments.add(
        this.ticket._id,
        this.newCommentMessage.trim(),
        this.isInternalNote
      );
      if (res.success) {
        this.newCommentMessage = '';
        this.isInternalNote = false;
        await this.loadComments();
        this.toast.success('Comment posted');
      }
    } catch (err: any) {
      this.toast.error(err.message || 'Failed to post comment');
    } finally {
      this.commentLoading = false;
    }
  }

  async submitRating() {
    this.ratingLoading = true;
    try {
      const res = await this.api.ratings.create({
        ticketId: this.ticket._id,
        score: this.selectedScore,
        comment: this.ratingComment.trim()
      });
      if (res.success) {
        this.existingRating = res.data;
        this.toast.success('Thank you for rating our service!');
        confetti({ particleCount: 80, spread: 80, origin: { y: 0.6 } });
        this.updated.emit();
      }
    } catch (err: any) {
      this.toast.error(err.message || 'Rating submission failed');
    } finally {
      this.ratingLoading = false;
    }
  }
}

// client/src/components/TicketDetailModal.jsx
import React, { useState, useEffect, useRef } from 'react';
import { 
  X, 
  Send, 
  Clock, 
  User, 
  Tag, 
  Flame, 
  CheckCircle2, 
  Lock, 
  MessageSquare, 
  Star, 
  AlertTriangle,
  Play,
  Pause,
  Check,
  Zap,
  ShieldAlert
} from 'lucide-react';
import confetti from 'canvas-confetti';
import { api } from '../services/api';
import { getStatusBadge, getPriorityBadge, formatTimeRemaining } from './TicketCard';
import { joinTicketRoom, leaveTicketRoom, getSocket } from '../services/socket';

export function TicketDetailModal({ 
  ticket, 
  currentUser, 
  onClose, 
  onTicketUpdated, 
  addToast,
  allAgents = []
}) {
  const [activeTab, setActiveTab] = useState('discussion'); // 'discussion' | 'internal_notes'
  const [comments, setComments] = useState([]);
  const [newComment, setNewComment] = useState('');
  const [isInternalNote, setIsInternalNote] = useState(false);
  const [ratingScore, setRatingScore] = useState(5);
  const [ratingComment, setRatingComment] = useState('');
  const [existingRating, setExistingRating] = useState(null);
  const [escalateReason, setEscalateReason] = useState('');
  const [showEscalateModal, setShowEscalateModal] = useState(false);
  const [selectedAgentId, setSelectedAgentId] = useState(ticket?.assignedAgentId?._id || '');
  const [loading, setLoading] = useState(false);

  const commentsEndRef = useRef(null);

  if (!ticket) return null;

  const isStaff = currentUser?.role === 'agent' || currentUser?.role === 'manager' || currentUser?.role === 'admin';
  const isOwnerCustomer = currentUser?.role === 'customer' && (ticket.customerId?._id === currentUser?.id || ticket.customerId === currentUser?.id);
  const slaInfo = formatTimeRemaining(ticket.slaDueAt, ticket.status, ticket.isBreached);

  // Load comments & ratings and subscribe to WebSocket room
  useEffect(() => {
    if (!ticket._id) return;

    joinTicketRoom(ticket._id);

    const loadData = async () => {
      try {
        const cRes = await api.comments.list(ticket._id);
        setComments(cRes.data || []);
      } catch (err) {
        console.error('Error fetching comments:', err);
      }

      if (ticket.status === 'Resolved' || ticket.status === 'Closed') {
        try {
          const rRes = await api.ratings.getByTicket(ticket._id);
          setExistingRating(rRes.data);
        } catch {
          // No rating yet
          setExistingRating(null);
        }
      }
    };

    loadData();

    // Listen for incoming live socket events
    const socket = getSocket();
    const handleCommentAdded = ({ ticketId, comment }) => {
      if (ticketId === ticket._id) {
        setComments((prev) => [...prev, comment]);
      }
    };

    const handleInternalNote = ({ ticketId, comment }) => {
      if (ticketId === ticket._id && isStaff) {
        setComments((prev) => [...prev, comment]);
      }
    };

    if (socket) {
      socket.on('comment:added', handleCommentAdded);
      socket.on('comment:internal_note', handleInternalNote);
    }

    return () => {
      leaveTicketRoom(ticket._id);
      if (socket) {
        socket.off('comment:added', handleCommentAdded);
        socket.off('comment:internal_note', handleInternalNote);
      }
    };
  }, [ticket._id, isStaff]);

  useEffect(() => {
    commentsEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [comments]);

  // Handle Comment Submission
  const handleSendComment = async (e) => {
    e.preventDefault();
    if (!newComment.trim()) return;

    try {
      const isInternal = isStaff ? isInternalNote : false;
      const res = await api.comments.add(ticket._id, newComment.trim(), isInternal);
      setNewComment('');
      addToast('success', isInternal ? 'Internal Note Logged' : 'Comment Posted', 'Sent to live channel.');
    } catch (err) {
      addToast('error', 'Failed to Send', err.message);
    }
  };

  // State Transition Handlers
  const handleTransition = async (nextStatus) => {
    setLoading(true);
    try {
      const res = await api.tickets.updateStatus(ticket._id, nextStatus);
      addToast('success', 'Status Transitioned', `Ticket is now marked as '${nextStatus}'.`);
      if (onTicketUpdated) onTicketUpdated({ ...ticket, status: nextStatus });
    } catch (err) {
      addToast('error', 'Transition Rejected', err.message);
    } finally {
      setLoading(false);
    }
  };

  // Assignment Handlers
  const handleManualAssign = async (agentId) => {
    if (!agentId) return;
    try {
      const res = await api.tickets.assign(ticket._id, agentId);
      addToast('success', 'Ticket Assigned', 'Assigned agent updated.');
      if (onTicketUpdated) onTicketUpdated({ ...ticket, assignedAgentId: res.data.assignedAgentId, status: res.data.status });
    } catch (err) {
      addToast('error', 'Assignment Failed', err.message);
    }
  };

  const handleAutoAssign = async () => {
    try {
      const res = await api.tickets.autoAssign(ticket._id);
      addToast('success', 'Auto-Dispatched', `Auto-assigned to ${res.data.assignedAgent.name} (lowest workload).`);
      if (onTicketUpdated) onTicketUpdated({ ...ticket, assignedAgentId: res.data.assignedAgent, status: res.data.status });
    } catch (err) {
      addToast('error', 'Auto-Assign Failed', err.message);
    }
  };

  // Escalation Handler
  const handleEscalate = async (e) => {
    e.preventDefault();
    try {
      const res = await api.tickets.escalate(ticket._id, escalateReason);
      addToast('alert', 'Ticket Escalated', 'Priority boosted and reassigned to Senior Management.');
      setShowEscalateModal(false);
      if (onTicketUpdated) onTicketUpdated({ ...ticket, isEscalated: true, priority: res.data.priority });
    } catch (err) {
      addToast('error', 'Escalation Failed', err.message);
    }
  };

  // Rating Submission Handler
  const handleRatingSubmit = async (e) => {
    e.preventDefault();
    try {
      const res = await api.ratings.create({
        ticketId: ticket._id,
        score: ratingScore,
        comment: ratingComment
      });
      setExistingRating(res.data);
      confetti({ particleCount: 80, spread: 60, origin: { y: 0.7 } });
      addToast('success', 'Feedback Submitted', 'Ticket is now finalized and Closed. Thank you!');
      if (onTicketUpdated) onTicketUpdated({ ...ticket, status: 'Closed' });
    } catch (err) {
      addToast('error', 'Rating Error', err.message);
    }
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()} style={{ maxWidth: '840px', height: '88vh' }}>
        {/* Header */}
        <div style={{ padding: '18px 24px', borderBottom: '1px solid var(--border-glass)', display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '16px' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}>
              <span style={{ fontFamily: 'monospace', color: 'var(--text-subtle)', fontSize: '12px' }}>
                #{ticket._id?.slice(-6).toUpperCase()}
              </span>
              {getStatusBadge(ticket.status)}
              {getPriorityBadge(ticket.priority)}
              {ticket.isEscalated && (
                <span className="badge" style={{ background: 'rgba(168, 85, 247, 0.2)', color: '#c084fc', border: '1px solid rgba(168, 85, 247, 0.4)' }}>
                  <Flame size={12} /> Escalated
                </span>
              )}
            </div>
            <h2 style={{ fontSize: '18px', fontWeight: '800', color: '#fff', lineHeight: 1.3 }}>{ticket.title}</h2>
          </div>
          <button onClick={onClose} style={{ background: 'transparent', border: 'none', color: 'var(--text-subtle)', cursor: 'pointer', padding: '4px' }}>
            <X size={20} />
          </button>
        </div>

        {/* SLA & Meta Quick Bar */}
        <div style={{ padding: '10px 24px', background: 'var(--bg-surface-elevated)', borderBottom: '1px solid var(--border-glass)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '10px', fontSize: '12px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
            <span style={{ color: 'var(--text-muted)' }}>
              Category: <strong style={{ color: '#fff' }}>{ticket.category}</strong>
            </span>
            <span style={{ color: 'var(--text-muted)' }}>
              Customer: <strong style={{ color: '#fff' }}>{ticket.customerId?.name || 'Customer'}</strong>
            </span>
            <span style={{ color: 'var(--text-muted)' }}>
              Assignee: <strong style={{ color: ticket.assignedAgentId ? 'var(--cyan)' : 'var(--amber)' }}>{ticket.assignedAgentId?.name || 'Unassigned'}</strong>
            </span>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '6px', color: slaInfo.color, fontWeight: '700' }}>
            <Clock size={14} />
            <span>{slaInfo.text}</span>
          </div>
        </div>

        {/* Action Controls Toolbar */}
        <div style={{ padding: '12px 24px', background: 'rgba(0,0,0,0.2)', borderBottom: '1px solid var(--border-glass)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '10px' }}>
          {/* Status Transitions */}
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}>
            <span style={{ fontSize: '12px', fontWeight: '700', color: 'var(--text-subtle)' }}>Actions:</span>
            {ticket.status === 'Open' && isStaff && (
              <button onClick={() => handleTransition('In Progress')} disabled={loading} className="btn btn-primary btn-sm">
                <Play size={13} /> Start In Progress
              </button>
            )}
            {ticket.status === 'In Progress' && isStaff && (
              <>
                <button onClick={() => handleTransition('On Hold')} disabled={loading} className="btn btn-secondary btn-sm">
                  <Pause size={13} /> Put On Hold
                </button>
                <button onClick={() => handleTransition('Resolved')} disabled={loading} className="btn btn-emerald btn-sm">
                  <CheckCircle2 size={13} /> Mark Resolved
                </button>
              </>
            )}
            {ticket.status === 'On Hold' && isStaff && (
              <>
                <button onClick={() => handleTransition('In Progress')} disabled={loading} className="btn btn-primary btn-sm">
                  <Play size={13} /> Resume In Progress
                </button>
                <button onClick={() => handleTransition('Resolved')} disabled={loading} className="btn btn-emerald btn-sm">
                  <CheckCircle2 size={13} /> Mark Resolved
                </button>
              </>
            )}
            {ticket.status === 'Resolved' && (currentUser?.role === 'customer' || currentUser?.role === 'manager' || currentUser?.role === 'admin') && (
              <>
                <button onClick={() => handleTransition('Closed')} disabled={loading} className="btn btn-secondary btn-sm">
                  <Check size={13} /> Finalize & Close
                </button>
                <button onClick={() => handleTransition('In Progress')} disabled={loading} className="btn btn-secondary btn-sm">
                  Reopen Ticket
                </button>
              </>
            )}

            {/* Escalation Button (if not already escalated) */}
            {ticket.status !== 'Closed' && !ticket.isEscalated && isStaff && (
              <button onClick={() => setShowEscalateModal(true)} className="btn btn-sm" style={{ background: 'rgba(168, 85, 247, 0.2)', color: '#c084fc', border: '1px solid rgba(168, 85, 247, 0.4)' }}>
                <Flame size={13} /> Escalate Ticket
              </button>
            )}
          </div>

          {/* Manager Dispatcher Quick Controls */}
          {(currentUser?.role === 'manager' || currentUser?.role === 'admin') && ticket.status !== 'Closed' && (
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <button onClick={handleAutoAssign} className="btn btn-secondary btn-sm" title="Auto-Assign to least loaded agent">
                <Zap size={13} color="var(--amber)" /> Auto-Assign
              </button>
              {allAgents.length > 0 && (
                <select 
                  className="form-select" 
                  style={{ padding: '4px 8px', fontSize: '12px' }}
                  value={selectedAgentId}
                  onChange={(e) => {
                    setSelectedAgentId(e.target.value);
                    handleManualAssign(e.target.value);
                  }}
                >
                  <option value="">Reassign Agent...</option>
                  {allAgents.map((ag) => (
                    <option key={ag._id} value={ag._id}>{ag.name}</option>
                  ))}
                </select>
              )}
            </div>
          )}
        </div>

        {/* Modal Body: Description + Timeline */}
        <div style={{ flex: 1, overflowY: 'auto', padding: '20px 24px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
          {/* Ticket Description Box */}
          <div style={{ background: 'var(--bg-surface-elevated)', borderRadius: 'var(--radius-md)', padding: '14px 18px', border: '1px solid var(--border-glass)' }}>
            <div style={{ fontSize: '11px', fontWeight: '700', color: 'var(--text-subtle)', textTransform: 'uppercase', marginBottom: '4px' }}>
              Issue Description
            </div>
            <p style={{ fontSize: '14px', color: 'var(--text-main)', lineHeight: 1.5, whiteSpace: 'pre-wrap' }}>
              {ticket.description}
            </p>
          </div>

          {/* Rating Display or Rating Form for Customer */}
          {(ticket.status === 'Resolved' || ticket.status === 'Closed') && (
            <div style={{ background: 'rgba(16, 185, 129, 0.08)', border: '1px solid rgba(16, 185, 129, 0.3)', borderRadius: 'var(--radius-md)', padding: '16px 20px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
                <Star size={18} color="#f59e0b" fill="#f59e0b" />
                <h4 style={{ fontSize: '14px', fontWeight: '700', color: '#fff' }}>Customer Satisfaction Rating</h4>
              </div>

              {existingRating ? (
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '4px' }}>
                    {[1, 2, 3, 4, 5].map((s) => (
                      <Star key={s} size={16} color="#f59e0b" fill={s <= existingRating.score ? '#f59e0b' : 'none'} />
                    ))}
                    <span style={{ fontSize: '13px', fontWeight: '700', color: '#fff', marginLeft: '6px' }}>
                      {existingRating.score} / 5 Stars
                    </span>
                  </div>
                  {existingRating.comment && (
                    <p style={{ fontSize: '13px', color: 'var(--text-muted)', fontStyle: 'italic', marginTop: '4px' }}>
                      "{existingRating.comment}"
                    </p>
                  )}
                </div>
              ) : isOwnerCustomer && ticket.status === 'Resolved' ? (
                <form onSubmit={handleRatingSubmit} style={{ marginTop: '8px' }}>
                  <p style={{ fontSize: '12px', color: 'var(--text-muted)', marginBottom: '10px' }}>
                    How would you rate the speed and resolution quality provided by our support team?
                  </p>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '12px' }}>
                    {[1, 2, 3, 4, 5].map((star) => (
                      <button
                        key={star}
                        type="button"
                        onClick={() => setRatingScore(star)}
                        style={{ background: 'transparent', border: 'none', cursor: 'pointer' }}
                      >
                        <Star size={24} color="#f59e0b" fill={star <= ratingScore ? '#f59e0b' : 'none'} />
                      </button>
                    ))}
                    <span style={{ fontSize: '13px', fontWeight: '700', color: 'var(--amber)', marginLeft: '8px' }}>
                      {ratingScore} Stars
                    </span>
                  </div>
                  <input
                    type="text"
                    className="form-input"
                    placeholder="Optional feedback comment (e.g., Quick turnaround, thanks!)..."
                    value={ratingComment}
                    onChange={(e) => setRatingComment(e.target.value)}
                    style={{ marginBottom: '10px' }}
                  />
                  <button type="submit" className="btn btn-emerald btn-sm">
                    Submit Rating & Close Ticket
                  </button>
                </form>
              ) : (
                <span style={{ fontSize: '12px', color: 'var(--text-subtle)' }}>Awaiting customer rating feedback.</span>
              )}
            </div>
          )}

          {/* Comment Stream Timeline */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            <div style={{ fontSize: '12px', fontWeight: '700', color: 'var(--text-subtle)', textTransform: 'uppercase', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <MessageSquare size={14} /> Communication History ({comments.length})
            </div>

            {comments.length === 0 ? (
              <div style={{ padding: '24px', textAlign: 'center', color: 'var(--text-subtle)', fontSize: '13px' }}>
                No comments or internal notes yet. Start the conversation below.
              </div>
            ) : (
              comments.map((c) => {
                const isInternal = c.isInternal;
                return (
                  <div
                    key={c._id || Math.random()}
                    style={{
                      padding: '12px 16px',
                      borderRadius: 'var(--radius-md)',
                      background: isInternal ? 'rgba(168, 85, 247, 0.12)' : 'var(--bg-surface-elevated)',
                      border: isInternal ? '1px solid rgba(168, 85, 247, 0.35)' : '1px solid var(--border-glass)'
                    }}
                  >
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '6px' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                        <span style={{ fontSize: '13px', fontWeight: '700', color: isInternal ? '#c084fc' : '#fff' }}>
                          {c.authorId?.name || 'User'}
                        </span>
                        <span style={{ fontSize: '10px', textTransform: 'capitalize', color: 'var(--text-subtle)' }}>
                          ({c.authorId?.role || 'staff'})
                        </span>
                        {isInternal && (
                          <span className="badge" style={{ background: 'rgba(168, 85, 247, 0.25)', color: '#d8b4fe', fontSize: '9px' }}>
                            <Lock size={10} /> STAFF ONLY NOTE
                          </span>
                        )}
                      </div>
                      <span style={{ fontSize: '11px', color: 'var(--text-subtle)' }}>
                        {c.createdAt ? new Date(c.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : ''}
                      </span>
                    </div>
                    <p style={{ fontSize: '13px', color: 'var(--text-main)', lineHeight: 1.4 }}>
                      {c.message}
                    </p>
                  </div>
                );
              })
            )}
            <div ref={commentsEndRef} />
          </div>
        </div>

        {/* Comment Input Composer */}
        {ticket.status !== 'Closed' ? (
          <form onSubmit={handleSendComment} style={{ padding: '16px 24px', borderTop: '1px solid var(--border-glass)', background: 'var(--bg-surface-elevated)', display: 'flex', flexDirection: 'column', gap: '10px' }}>
            {isStaff && (
              <div style={{ display: 'flex', alignItems: 'center', gap: '16px', fontSize: '12px' }}>
                <label style={{ display: 'flex', alignItems: 'center', gap: '6px', cursor: 'pointer', color: !isInternalNote ? 'var(--cyan)' : 'var(--text-subtle)', fontWeight: '600' }}>
                  <input
                    type="radio"
                    name="commentType"
                    checked={!isInternalNote}
                    onChange={() => setIsInternalNote(false)}
                  />
                  Public Reply (Visible to Customer)
                </label>
                <label style={{ display: 'flex', alignItems: 'center', gap: '6px', cursor: 'pointer', color: isInternalNote ? '#c084fc' : 'var(--text-subtle)', fontWeight: '600' }}>
                  <input
                    type="radio"
                    name="commentType"
                    checked={isInternalNote}
                    onChange={() => setIsInternalNote(true)}
                  />
                  <Lock size={12} /> Staff Internal Note (Strict Privacy Isolation)
                </label>
              </div>
            )}

            <div style={{ display: 'flex', gap: '10px' }}>
              <input
                type="text"
                className="form-input"
                placeholder={isInternalNote ? 'Log private troubleshooting notes (hidden from customer)...' : 'Type a reply to the customer...'}
                value={newComment}
                onChange={(e) => setNewComment(e.target.value)}
                style={{ flex: 1 }}
              />
              <button type="submit" className={isInternalNote ? 'btn btn-secondary' : 'btn btn-primary'}>
                <Send size={15} /> Send
              </button>
            </div>
          </form>
        ) : (
          <div style={{ padding: '14px', textAlign: 'center', background: 'var(--bg-surface-elevated)', borderTop: '1px solid var(--border-glass)', color: 'var(--text-subtle)', fontSize: '12px' }}>
            This ticket is closed. Discussion and notes are locked.
          </div>
        )}

        {/* Escalation Prompt Sub-Modal */}
        {showEscalateModal && (
          <div className="modal-overlay" style={{ background: 'rgba(0,0,0,0.85)' }}>
            <div className="modal-content" style={{ maxWidth: '480px', padding: '20px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '12px' }}>
                <ShieldAlert size={22} color="var(--purple)" />
                <h3 style={{ fontSize: '16px', fontWeight: '800', color: '#fff' }}>Escalate to Senior Management</h3>
              </div>
              <p style={{ fontSize: '13px', color: 'var(--text-muted)', marginBottom: '14px' }}>
                Escalating increases ticket priority and reassigns it to the executive manager queue.
              </p>
              <form onSubmit={handleEscalate}>
                <div className="form-group">
                  <label className="form-label">Reason for Escalation *</label>
                  <textarea
                    className="form-textarea"
                    rows={3}
                    placeholder="e.g. Critical revenue-impacting bug or imminent SLA breach..."
                    value={escalateReason}
                    onChange={(e) => setEscalateReason(e.target.value)}
                    required
                  />
                </div>
                <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '10px', marginTop: '14px' }}>
                  <button type="button" onClick={() => setShowEscalateModal(false)} className="btn btn-secondary btn-sm">
                    Cancel
                  </button>
                  <button type="submit" className="btn btn-primary btn-sm" style={{ background: 'var(--purple)' }}>
                    Confirm Escalation
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
